name: Assign Review

on:
   pull_request:
     branches: [ main ]

jobs:
  assign_review:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Assign Reviewer
        uses: ./assign_review

