name: Delete Tags
on:
  workflow_dispatch:

env:
  ENV_TOKEN: ${{ secrets.DOOR }}
  REPO: "myrepo3"
jobs:
  Execute_Versioning:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
        
    - name: Delete tags
      run: |
       git config --global user.email "github-actions[bot]@users.noreply.github.com"
       git config --global user.name "github-actions[bot]"
       git tag -l | xargs -n 1 git push --delete origin
       git tag | xargs git tag -d
       
