name: Deploy

on:
  # push:
  #   branches: [main]
  workflow_dispatch:
env:
  ENV_TOKEN: ${{ secrets.SECRET_TOKEN }}
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Call SH
        run: |
        chmod +x ./script/gh_release.sh
        ./script/gh_release.sh $ENV_TOKEN