name: Create GH Release

on:
  push:
    branches: [main]
    paths:
      - 'VERSION'

env:
  ENV_TOKEN: ${{ secrets.DOOR }}
jobs:
 GH_Release:
  runs-on: ubuntu-latest
  steps:
    - name: Checkout Code
      uses: actions/checkout@v3
      with: 
          fetch-depth: 0
    - name: Getting Version
      run: |
       ver_str=$(cat "VERSION")
       ver_extract_str="$(cut -d' ' -f2 <<< "$ver_str")"
       echo "Version string is $ver_extract_str"
       echo "ver_extract_str=${ver_extract_str}" >> $GITHUB_ENV
       echo "env version " $ver_extract_str
       echo "gitmojiko=':sparkle:" >> $GITHUB_ENV

    - name: Call SH
      run: |
        chmod +x ./script/gh_release.sh
        ./script/gh_release.sh $ENV_TOKEN $ver_extract_str
