name: Create GH Release

on:
  push:
    branches: [main]
    paths:
      - 'VERSION'

env:
  ENV_TOKEN: ${{ secrets.DOOR }}
jobs:
 GH_Release:
  runs-on: ubuntu-latest
  steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Call SH
      run: |
        chmod +x ./script/gh_release2.sh
        ./script/gh_release2.sh $ENV_TOKEN "0.2.4"
