name: Versioning
on:
  # pull_request:
  #   branches: [ main ]
  #   types: [closed]
  push:
     branches: [main]
  #    paths-ignore:
  #    - 'VERSION'
  workflow_dispatch:

env:
  ENV_TOKEN: ${{ secrets.DOOR }}
  # ENV_MSG: $(git log -1 --pretty=format:"%s")  #${{ github.event.head_commit.message }}
jobs:
  Execute_Versioning:
    # if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    outputs:
      ENV_GM: ${{ steps.setvar.outputs.gitmo }}
      ENV_VER: ${{ steps.setvar.outputs.sh_ver }}
      ENV_MSG: ${{ steps.ci.outputs.message }}
    #if: "!contains(github.event.head_commit.message, '[JOB] Push version')"
    steps:
    - uses: actions/checkout@v3
    - name: Retrieve Defaults
      run: |
        chmod +x ./script/get_defaults.sh
        ./script/get_defaults.sh $ENV_TOKEN
